#!/bin/sh

# Copyright Claes Holmerson
# This program can be distributed under the terms of the GNU GPL v2.

usage() 
{
    echo "Compose email for mailto-url in the default browser"
    echo "Usage: $0 {yahoo|gmail|'compose-url format'} mailto-url"
    echo 
    echo "'compose-url format' defines how a specific url should be formatted for"
    echo "a specific webmail provider"
    echo "The query string arguments must defined using '%s' (printf-style), in order "
    echo "for TO, SUBJECT, CC, BCC and BODY."
    echo "Note that since single percent signs are parsed by printf this way, "
    echo "proper percent signs that belong to the URL must be escaped using %%"
    echo
    echo "Examples: "
    echo "$0 yahoo 'mailto:joe@example.com?cc=bob@example.com&body=hello&subject=hi'"
    echo "or"
    echo "$0 'http://compose.mail.yahoo.com/?To=%s&Subject=%s&Cc=%s&Bcc=%s&Body=%s' 'mailto:joe@example.com?cc=bob@example.com&body=hello&subject=hi'"
    echo
    echo "Note also: mailto-url should be url-encoded"
}

if [ ! $# == 2 ]; then
  usage
  exit 1
fi

PROVIDER_URL=
MAILTO_URL=$2

#Parse mailto URL
export TO=$(echo "$MAILTO_URL" | grep -oE "mailto:[A-Za-z0-9@\_\.\-]+" | cut -d ':' -f 2 )
export CC=$(echo "$MAILTO_URL" | grep -oE "(^|[?&])cc=[^&]+" | cut -f 2 -d "=" )   
export BCC=$(echo "$MAILTO_URL" | grep -oE "(^|[?&])bcc=[^&]+" | cut -f 2 -d "=" )   
export SUBJECT=$(echo "$MAILTO_URL" | grep -oE "(^|[?&])subject=[^&]+" | cut -f 2 -d "=" )
export BODY=$(echo "$MAILTO_URL" | grep -oE "(^|[?&])body=[^&]+" | cut -f 2 -d "=" )

case "$1" in 
    yahoo)
	PROVIDER_URL="http://compose.mail.yahoo.com/?To=$TO&Subject=$SUBJECT&Cc=$CC&Bcc=$BCC&Body=$BODY"
	;;
    gmail)
	PROVIDER_URL="http://mail.google.com/mail/?view=cm&fs=1&to=$TO&su=$SUBJECT&cc=$CC&bcc=$BCC&body=$BODY&tf=1"
	;;
    *)
	PROVIDER_URL=$(printf "$1" ${TO:=''} ${SUBJECT:=''} ${CC:=''} ${BCC:=''} ${BODY:=''})
esac
#echo $PROVIDER_URL
xdg-open "$PROVIDER_URL"



